language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - SYMFONY_VERSION=4.4.*
  - SYMFONY_VERSION=5.0.*

install:
  - if [ "$SYMFONY_VERSION" = "5.0.*" ]; then composer require behat/behat:dev-master --no-update --no-scripts --prefer-dist; fi
  - composer require symfony/config:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
  - composer update --no-progress

script:
  - vendor/bin/phpspec run -f pretty
  - vendor/bin/behat -fprogress --strict
